name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        # Replace <project-name> with your actual project name from angular.json
        run: bun run build --configuration=production --base-href /kraiwith.github.io/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Angular builds to dist/<project-name>/browser by default in newer versions
          path: ./dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
